const mongoose = require('mongoose');
const { Schema } = mongoose;

const tradeSchema = new Schema(
  {
    id: { type: String, required: true },
    author: { type: String, required: true },
    totalOffers: { type: Number, default: 0 },
    totalWants: { type: Number, default: 0 },
    info: { type: String, default: '' },
    comments: [
      {
        id: { type: String, required: true },
        content: { type: String, default: '' },
        date: { type: Number, required: true },
        authorName: { type: String, required: true },
        authorId: { type: String, required: true },
        authorIsPremium: { type: Boolean, default: false },
        authorIsAdmin: { type: Boolean, default: false },
        authorPic: { type: String, default: '' },
      },
    ],
    offers: {
      highlight: {
        market_hash_name: { type: String, default: 'unknown item' },
        pureName: { type: String, default: 'unknown item' },
        longerWear: { type: String, default: 'unknown wear' },
        wear: { type: String, default: 'no wear' },
        price: { type: String, default: 'unknown price' },
        priceValue: { type: Number, default: 0 },
        priceRecord: { type: Object, default: {} },
        color: { type: String, default: 'FFFFFF' },
        pic: { type: String, default: '' },
        type: { type: String, default: '' },
        inspect: { type: String, default: '' },
        floatvalue: { type: Number, default: undefined },
        origin: { type: String, default: '' },
        minFloat: { type: Number, default: undefined },
        maxFloat: { type: Number, default: undefined },
        paintseed: { type: Number, default: undefined },
        defindex: { type: Number, default: undefined },
        paintindex: { type: Number, default: undefined },
        stickers: [
          {
            stickerId: { type: Number, default: undefined },
            slot: { type: Number, default: undefined },
            codename: { type: String, default: '' },
            material: { type: String, default: '' },
            name: { type: String, default: '' },
          },
        ],
        weapon_type: { type: String, default: '' },
        gun_type: { type: String, default: '' },
        exterior: { type: String, default: '' },
        rarity: { type: String, default: '' },
        isStatTrak: { type: Boolean, required: true },
        isSouvenir: { type: Boolean, required: true },
        classid: { type: String, default: 'unknown classid' },
      },
      other: [
        {
          market_hash_name: { type: String, default: 'unknown item' },
          pureName: { type: String, default: 'unknown item' },
          longerWear: { type: String, default: 'unknown wear' },
          wear: { type: String, default: 'no wear' },
          price: { type: String, default: 'unknown price' },
          priceValue: { type: Number, default: 0 },
          priceRecord: { type: Object, default: {} },
          color: { type: String, default: 'FFFFFF' },
          pic: { type: String, default: '' },
          type: { type: String, default: '' },
          inspect: { type: String, default: '' },
          floatvalue: { type: Number, default: undefined },
          origin: { type: String, default: '' },
          minFloat: { type: Number, default: undefined },
          maxFloat: { type: Number, default: undefined },
          paintseed: { type: Number, default: undefined },
          defindex: { type: Number, default: undefined },
          paintindex: { type: Number, default: undefined },
          stickers: [
            {
              stickerId: { type: Number, default: undefined },
              slot: { type: Number, default: undefined },
              codename: { type: String, default: '' },
              material: { type: String, default: '' },
              name: { type: String, default: '' },
            },
          ],
          weapon_type: { type: String, default: '' },
          gun_type: { type: String, default: '' },
          exterior: { type: String, default: '' },
          rarity: { type: String, default: '' },
          isStatTrak: { type: Boolean, required: true },
          isSouvenir: { type: Boolean, required: true },
          classid: { type: String, default: 'unknown classid' },
        },
      ],
    },
    wants: {
      highlight: {
        market_hash_name: { type: String, default: 'unknown item' },
        pureName: { type: String, default: 'unknown item' },
        longerWear: { type: String, default: 'unknown wear' },
        wear: { type: String, default: 'no wear' },
        price: { type: String, default: 'unknown price' },
        priceValue: { type: Number, default: 0 },
        priceRecord: { type: Object, default: {} },
        color: { type: String, default: 'FFFFFF' },
        pic: { type: String, default: '' },
        type: { type: String, default: '' },
        weapon_type: { type: String, default: '' },
        gun_type: { type: String, default: '' },
        exterior: { type: String, default: '' },
        rarity: { type: String, default: '' },
        isStatTrak: { type: Boolean, required: true },
        isSouvenir: { type: Boolean, required: true },
        classid: { type: String, default: 'unknown classid' },
      },
      other: [
        {
          market_hash_name: { type: String, default: 'unknown item' },
          pureName: { type: String, default: 'unknown item' },
          longerWear: { type: String, default: 'unknown wear' },
          wear: { type: String, default: 'no wear' },
          price: { type: String, default: 'unknown price' },
          priceValue: { type: Number, default: 0 },
          priceRecord: { type: Object, default: {} },
          color: { type: String, default: 'FFFFFF' },
          pic: { type: String, default: '' },
          type: { type: String, default: '' },
          weapon_type: { type: String, default: '' },
          gun_type: { type: String, default: '' },
          exterior: { type: String, default: '' },
          rarity: { type: String, default: '' },
          isStatTrak: { type: Boolean, required: true },
          isSouvenir: { type: Boolean, required: true },
          classid: { type: String, default: 'unknown classid' },
        },
      ],
    },
  },
  { timestamps: true }
);

tradeSchema.index({ market_hash_name: 'text' });

module.exports = mongoose.model('Trade', tradeSchema);
